### PR TITLE
Implementation Agnostic API

### PR DESCRIPTION
**Pull request by agent6262**
I am attempting to make JOML implementation agnostic with respect to this issue #144 . I attempted to stick to some sort of code formatting but it was all over the place; If any thing needs to be changed let me know.

### CODE REVIEW

**Comment by httpdigest** [comment]
Great work so far!

There is only one thing which makes this a major API break:
You cannot write `Matrix4f m = new Matrix4f().translate(1, 2, 3)` anymore, because now you have to use the abstract class `Matrix4fc m = new Matrix4f().translate(1, 2, 3)` since that is the currently invariant return type of every method overridden by Matrix4f and we currently cannot use covariant return types (that requires Java 1.5).

This is very unfortunate, since every code, article, documentation and book about/using JOML has to be edited to include this API change.

One thing to remedy this would require the following changes:
- `Matrix4f.translate()` cannot simply delegate to `Matrix4f.translate(..., dest)` anymore but has to handle the `dest = this` case explicitly
- Up the runtime requirements to Java 1.5 (unfortunate 'cause this excludes JavaME - but this can probably be handled via automatic backporting)
- Use covariant return types in the implementing methods (i.e. `Matrix4f.translate()` must use `Matrix4f` as return type, whereas `Matrix4f.translate(..., dest)` must still use the invariant parameter type as return type)

So, no matter what we do, we always pay the price somewhere.
This is why I still prefer an automatic code-generation built-time process which can generate a version of JOML for any identified use-case and does not have to rely on Java language semantics to hopefully play nicely with any generified/abstracted solution for every such use-case.

**Comment by agent6262** [comment]
Thanks!

**Comment by agent6262** [comment]
Thanks!

To address some of the concerns.
If you are worried about the documentation because of the API change to invariant return types, I have no problem making changes to those as well if you/we think this pr is acceptable the way it is. With that being said on the implementation front I would like to use covariant return types (which means going to JRE 1.5), however if that goes against JOML's goals then we could shoot for something else.

Possible order of fixes
1. Update documentation (I will be happy to make all the needed changes).
2. Up the runtime requirements to JRE 1.5.
3. Something else???

**Comment by httpdigest** [comment]
Thank you for your willingness to put so much effort into it! I really appreciate it and it's a real relief not having to do it all on my own.

If I am not mistaken, there does not need to be a change in the Javadocs, since those do not tell the return type, am I right? They only ever say "return this" or "return dest", which is totally okay/correct. So, the covariant overrides also do not need to copy the JavaDocs of the base class or anything like that.

So, if you want to incorporate those changes, that'd be great. Also, probably get rid of the subpackages in the org.joml.api package. The implementation package org.joml does not have them and so it looks somewhat odd that the API is separated into quaterion, matrix and vector subpackages. In my opinion the package separation is not really needed.

I'm also not sure whether the 'c' suffix is a good name for the base classes anymore. Since we already lost compatibility with code using the 'c' classes anyways (i.e. different package and no "writing to dest parameter" methods anymore) we could as well rename them. (I am fine with breaking API with those 'c' classes, since I assume that _most_ people will not use them.)
Maybe follow common Java naming patterns for them now and call them AbstractX, like "AbstractMatrix4f". Or, maybe even better "AMatrix4f" (which also sounds kinda nice when spoken :).

The upgrade to Java 1.5 is fine.

If those things are in, and all test/demo programs run with it then I will merge the PR.
You can find demos to test against in the JOML/joml-lwjgl3-demos and LWJGL/lwjgl3-demos repositories.

While you're at it, you could also update the version in the pom.xml and build.gradle files to 2.0.0-SNAPSHOT. That big of a change (up to 1.5 and API break of the 'c' classes plus of course API and impl separation) somewhat screams for a major version number increase. :)

**Comment by httpdigest** [comment]
My only _real_ worry is that when you start implementing immutable classes on top of the abstract classes or the interfaces it will break the 'L' in S.O.L.I.D (i.e. the Liskov Substitution Principle). That means, people cannot simply swap out the implementation class and expect code to (obversably) behave as before, within the bounds of the interface contract specified by the base class/interface:
```Java
AMatrix4f m1 = new Matrix4f();
AMatrix4f m2 = m1.rotateX(0.123f).translate(1, 2, 3);
assert m1 == m2;
```
I guess the really bad thing is that mutability is actually part of the contract of the abstract base classes/interfaces already. That should not be in there if we were to have both mutable and immutable implementations. So, the JavaDocs of the base classes/interfaces need to be changed to not say "return this" but instead just "return the result" (or something like that), which does not convey any information about object identity.
For the JavaDocs to not be copy/pasted into all the mutable/immutable classes in order to just write "return this" and "return a new instance" all the time, that could be stated in the class JavaDoc instead.

**Comment by httpdigest** [comment]
Another semantic issue/inconsistency you will run into when implementing immutable classes on top of the abstract classes or interfaces is, that you will have to implement the interface methods taking a `dest` parameter of the abstract class type, which is somewhat illogical when dealing with immutable classes.
This was the reason why the current master version uses the mutable implementation class as parameter type for the `dest` parameter, since it has to be assumed to be mutable.
So, the aspect of supporting immutability in the classes cannot be dealt with using the current interfaces.

**Comment by httpdigest** [comment]
I've done a bit of class designing, given the constraints we currently have, and came up with this:
joml2
So, whether anything is immutable is merely a property of the implementation class and not whether it exposes an interface only providing "getter"/non-modifying methods. In my opinion, we only need a single interface and then the mutable and immutable implementation classes.

**Comment by agent6262** [comment]
Thank you for the speedy replies!

I have thought a lot about what you are suggesting in your latest post. As far as I can tell, the API changes you are proposing would not easily allow for independent implementations to interact with the library. For example your API proposal resembles the current JOML API structure and because of that if I wanted to implement immutable and readonly class for my project, they would be unable to interact with some of the higher classes (like Vector3f (mutable)).

The following picture shows the difference between the two API concepts. For the "Implementation Agnostic API" The interfaces are read-only / immutable by nature and any class solely implementing it should also be treated as such (as seen with Vector3dr and Vector3di). And the abstract classes are designed to be mutable. Any class which extends an abstract class should also be mutable.

However with the "Modified Current API" which you are proposing seems to lock down the implementation to specifically JOML. The reason this could be an issue is in the event of a feature or class (lest say a read-only class) is missing the user would be unable to make a class which can interact with JOML, with out contributing.

capture

With your counter proposal the question that remains is weather to or not to make JOML "Implementation Agnostic". 
I am in favor of making JOML implementation agnostic hence this pr.

**Comment by httpdigest** [comment]
Obviously, I have little interest in putting any work into trying to convert JOML into an API that could theoretically be implemented by any other user in any other way. I mean, who would really do such a thing? People generally use JOML because it helps them with matrix/vector math and not because they want to implement their own math library on top of it.
JOML is not java.util or a logging facade, where it actually makes sense to have a way to build your own implementation on top of it, because there are lots of potential implementation choices. With matrix-vector multiplication there really is not many ways to do it.

Don't take me wrong: I _really_ appreciate your work on this, but the design we choose eventually will have to be based on the actual use-cases. If we want to support immutable classes, fine. Let's design the API for that. If in addition we want to have read-only classes (or read-only interfaces to any class), fine as well. Let's add this constraint and design an API that also fits this use-case. What we will likely not achieve is an API that abstracts over _everything_ and allows interaction of everything with everything else. That is simply not possible and also not economically feasible.

So, please let's define what _actual_ use-cases you want to cover with the API, taking into consideration that we would like to have full backwards compatibility, and then let's com up with a design that fits those use-cases as close as possible. The goal is _not_ to abstract over as much as possible, since that complicates the API and we will likely hit some Java language constraints or not meeting our goals/use-cases in trying to do so.

What I'd like to do is to define concrete use-cases for the aspects we want to cover (mutable, immutable, read-only, ...) with concrete small 1-2 line code examples and then try to come up with a solution to support that.

Thank you again for your work on this!

**Comment by agent6262** [comment]
I can see where you are coming from. I think the new API you proposed should work great, granted we stick to the design principles we lay out. 

I do agree with the way the API should present its self in the code snip-it you posted.

**Comment by agent6262** [comment]
Ill start working on  a new pr for this over Christmas.

**Pull request closed without merging**
