### PR TITLE
Add test cases for Vector2f/d.perpendicular()

### PR DESCRIPTION
**Pull request by pollend**
Organized relevant sections in TestUtil. grouped assertion and equal methods
for Quaternion.

### CODE REVIEW

**Comment by httpdigest** [comment]
Thanks, but again the reminder: https://github.com/JOML-CI/JOML/pull/231#issuecomment-622565903
Please use imperative mood and not past tense.

**Comment by httpdigest** [comment]
Okay, I've reworded the commit and merged.

**Comment by pollend** [comment]
I'll take not of that for future commits.

**Comment by httpdigest** [comment]
It's basically what you are already doing in the Terasology repo, e.g.:
- https://github.com/MovingBlocks/Terasology/commit/003cd89b08651853c3f6cf0234fb0ed939352a93
- https://github.com/MovingBlocks/Terasology/commit/fd25b8a605a41c5a226be2f153fb98569adef5b5

JOML just does not use semantic commit messages (yet). But the mood/tense is the same as in the above two commits of yours.
However, Terasology does not seem to use a consistent commit message style, so not all commits use semantic commit messages and not all use imperative mood but past tense "Added" instead of "Add".
@kBlaszczyk though seems to consistently follow the de-facto standard of starting with a verb in imperative form as explained in this great article: https://chris.beams.io/posts/git-commit/

**Comment by XenoAmess** [comment]
@httpdigest is already the most hardworking repo maintainer as I saw.
I have experieced hanged pr for several months in other guys' repos on github...That is really a bad experience.
And httpdigest, on the other hands, reply within 2 days everytime I create issur/pr, that is appreciated.
So I suggest everybody be calm and be happy, and not push him so much.
After all this is open source, and being enemy of others will gain no money.(another story in commercial world...)

**Comment by httpdigest** [comment]
Thanks, but no one is pushing me here. It's rather _me_ who's pushing others to follow a certain commit message style. :)

**Comment by pollend** [comment]
@httpdigest is just enforcing some patterns that I can pick up. seems like a pretty good opportunity to improve.

**Pull request merged**
