### PR TITLE
Move Gradle to 8.0, Update Plugins

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Comment by httpdigest** [comment]
Could you please reword "Bump some things" to something that describes the changes, and even better please make two separate commits for these changes, in total:
- "Update kotlin plugin and junit dependency"
- "Use https instead of http in URLs used in Maven pom.xml"

**Comment by JT122406** [comment]
> Could you please reword "Bump some things" to something that describes the changes, and even better please make two separate commits for these changes, in total:
> 
> * "Update kotlin plugin and junit dependency"
> * "Use https instead of http in URLs used in Maven pom.xml"

Handling it right now

**Comment by JT122406** [comment]
@httpdigest Should be good now

**Comment by httpdigest** [comment]
Thanks!

**Comment by JT122406** [comment]
@httpdigest Was the Gradle 8.0 commit reverted?

**Comment by httpdigest** [comment]
Yes, because it did not work. It failed to compile the Kotlin classes.
Did you try the build pipeline locally?

**Comment by JT122406** [comment]
> Yes, because it did not work. It failed to compile the Kotlin classes. Did you try the build pipeline locally?
> 
> The error was:
> 
> ```
> > Task :compileKotlin FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileKotlin'.
> > 'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
>   Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
> 
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/8.0/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 23s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```

I thought I did let me try it again and see what I can get

**Comment by httpdigest** [comment]
I tried and poked a bit myself and finally ended up with this working changes: https://github.com/JOML-CI/JOML/commit/5ef543f1ed84ac0ffb7b2a5b57d87a290677e587

**Comment by httpdigest** [comment]
I also needed to edit/rebase this commit https://github.com/JOML-CI/JOML/pull/327/commits/06868bc5e1c2d87dc4564eae08920b99c71ba6bb to https://github.com/JOML-CI/JOML/commit/d091ccc20e507a6ab429b05f2350f6d7c9350d15 because https://joml.org is not behind a TLS/HTTPS server with a certificate. It's merely a HTTP-redirect to the github site, implemented by my DNS hoster.

**Comment by JT122406** [comment]
ah gotcha

**Pull request merged**
