### PR TITLE
Fix parameter ordering in Quaternion#rotateYXZ

### PR DESCRIPTION
**Pull request by kBlaszczyk**
This PR fixes the parameter ordering of the `rotateYXZ()` method in the Quaternion classes.

### CODE REVIEW

**Comment by httpdigest** [comment]
Thanks! Can you also include a fix to Quaterniond in this PR and reword?

**Comment by kBlaszczyk** [comment]
done.

**Comment by httpdigest** [comment]
Thanks. Just a minor thing: I used the dot instead of the hash throughout the commit messages to separate a class name from its member.

**Comment by kBlaszczyk** [comment]
alright, noted.

**Comment by XenoAmess** [comment]
@httpdigest considering this pr and another pr earlier this year (about wrong order of x and y), 
should we do some work to create an auto-detector or something for such order things?
I think it should be possible, using PMD or something else to detect every java function, and wether contains ***x,***y,***z, and if their order be strange according to the function name, then warn when build.

**Pull request merged**
