### PR TITLE
Row Accessors for Matrix classes.

### PR DESCRIPTION
**Pull request by zmrodriguez91**
Added Row Accessors for Matrix classes.

### CODE REVIEW

**Comment by httpdigest** [comment]
First, thanks for you help!
Some comments I have on these:
- could you make one method which is parameterized with the row index as int (first parameter) and then throw an IndexOutOfBoundsException when feeding indices less than zero or greater than the size of the matrix-1?
- I fail to see the relevance in having access to a row of a matrix. Can you shed a bit of light on that? 
- I can see however that accessing a column might be useful, since these give the vectors which represent the mapping of the unit axes x, y and z in the transformation. So for symmetry with a possible getRow() method, can you also add getColumn() then?

Thanks!

**Comment by zmrodriguez91** [comment]
* I will change them parameterized versions and add getColumn() for symetry.
* I actually was going for the unit axes in the transformation with these methods. Perhaps I have the row and column subscripts transposed? =/

**Comment by zmrodriguez91** [comment]
The functions have been replaced with parameterized versions, and  the complimentary getColumn() methods were added.

**Comment by httpdigest** [comment]
Thank you for your additions to JOML!
It has been merged.

**Pull request merged**
