### PR TITLE
Preliminary implementation of 2D geometry classes.

### PR DESCRIPTION
**Pull request by dustContributor**
It has 2D integer based shapes:

* Shape2D, abstract class from which all 2D shapes inherit.
* AABR, axis aligned bounding rectangle (should be called rectangle probably :smile:).
* Triangle
* Circle

Tests implemented:

* isInside, which checks if a point is inside the shape.
* contains, which checks if one shape contains the other.
* intersect, which checks if two shapes intersect.

**NOTE** Triangle implementation of these is either incomplete or "approximated" by other shapes. Check the docs.

It has a "sort of" multiple dispatch mechanism so you can make method calls like shape2d.contains(otherShape2d) without knowing the type of each when calling. Internally it indexes into an array of method references to find the appropriate function.

The array of functions itself is a unique static array inside the shape sublcass. So there is one array for Circle, one for Triangle, and so on. They're passed to the constructor of Shape2D superclass. The method references are non-capturing lambdas in this case so they should be pretty fast to invoke.

### CODE REVIEW

**Comment by dustContributor** [comment]
Well yeah, build fails because it needs source level 8 to work :yum:

**Comment by httpdigest** [comment]
Thanks for your efforts!
Though, there are some things I'd like to discuss with this pull request:
First, like you said yourself, it does require 1.8 source and API level, so that alone is a no-go and I have to reject this pull request because of this at least.

Second, the formatting is completely different to the rest of JOML.

Third, none of the methods in OpsBounds have any reference to papers/articles/books that describe the algorithms implemented by them. You are of course free to come up with your own algorithm and the implementation thereof, but then I request that it be correct and tested. Right off the bat I see an issue with `OpsBounds.lineAabrIntersects`. It is prone to divide-by-zero when it is used with a vertical line, where x1==x2.
For those very commonly known things such as 2D geometric primitive intersection/containment tests I would request/require that a public source/article/book/paper is being implemented and referenced in the JavaDocs. I mean you can google right now for "rectangle line intersection" and probably find best algorithms there. Please do research before implementation.

Next thing is JavaDocs: Code in JOML requires to have full JavaDocs for all public methods, including parameter and return value comments. Most of your methods are lacking parameter JavaDocs.

Another issue: Code style. There is no need to make methods, parameters or local variables final. Since probably Java 1.2 doing so will not make execution a nanosecond faster.

Also, I'd like to try to make do with simply only the OpsBounds class without having to have Triangle, Circle and AABR by making all OpsBounds methods use the primitive parameters that constitute each such geometric type.
I currently see no use for the Shape2D class and its subtypes. They only seem to bloat the codebase with no obvious benefit.

On a more general note I am also not sure whether intersection/containment operations on geometric primitives are in JOML's scope. JOML is meant to be about matrices and vectors for very common operations in OpenGL rendering programs. In my opinion, such geometric operations do not fit that.
I see those operations rather as a separate library/framework. Of course, I myself have a whole host of things that I want to have in JOML, like facilities for constructive solid geometry or color conversion methods and also noise functions (like in GLM) but then I realize: That's not JOML. It should be another library. I fear that this is the case here, too.

**Comment by httpdigest** [comment]
I googled and stackoverflowed a bit for a line segment / rectangle intersection test, and found [this solution](http://stackoverflow.com/questions/32812265/fast-detecting-of-line-segment-and-rectangle-intersection-trough-cohen-sutherla#answer-32832812) to be a working one.
Refactoring a bit and making the assumption that the rectangle is axis-aligned, which the original solution did not seem to make, reduces that to:
```Java
/**
 * (JavaDocs omitted)
 *
 * Reference: http://stackoverflow.com/questions/32812265/fast-detecting-of-line-segment-and-rectangle-intersection-trough-cohen-sutherla#answer-32832812
 */
public static boolean lineIntersectRectangle(
        float x1, float y1, float x2, float y2,
        float minX, float minY, float maxX, float maxY) {
    if (x1 < minX && x2 < minX ||
        x1 > maxX && x2 > maxX ||
        y1 < minY && y2 < minY ||
        y1 > maxY && y2 > maxY)
        return false;
    float dy = y2 - y1;
    float dx = x1 - x2;
    float dxy = x2 * y1 - x1 * y2;
    float f1 = dy * minX + dx * minY + dxy;
    float f2 = dy * maxX + dx * minY + dxy;
    float f3 = dy * maxX + dx * maxY + dxy;
    float f4 = dy * minX + dx * maxY + dxy;
    if (f1 < 0 && f2 < 0 && f3 < 0 && f4 < 0)
        return false;
    if (f1 > 0 && f2 > 0 && f3 > 0 && f4 > 0)
        return false;
    return true;
}
```
So far this passes all tests with some arbitrary lines and rectangles.

**Comment by dustContributor** [comment]
> Another issue: Code style. There is no need to make methods, parameters or local variables final. Since probably Java 1.2 doing so will not make execution a nanosecond faster.

Final qualifier on parameters and local variables aren't even stored in the bytecode. They never made a difference in performance.

Its not about performance but intent. Everything is final unless I have a good reason to do otherwise. I say there is no reason **not** to make things final unless you have decided "I need this reference to be mutable" or "I need this method to be overridable". Forces you to think about mutability and inheritance more carefully.

Paraphrasing Mark Reinhold (in one of the latest JavaOne I believe), Java got all the wrong defaults: Classes can be subclassed by default, methods are overridable by default and locals/fields are mutable by default.

> First, like you said yourself, it does require 1.8 source and API level, so that alone is a no-go and I have to reject this pull request because of this at least.

No problem, as I said, this is "preliminary", make of that code what you will. Wasn't expecting to merge it right into the codebase, but you to review it if you thought some of it could be used. Thats the solution I have right now and it fits (part of) my purposes. Won't fit JOML's as it is.

> Second, the formatting is completely different to the rest of JOML.
And Java! I weep when I see that Java has camelCase but K&R style braces and C# has Allman braces but PascalCase naming :'(

> I currently see no use for the Shape2D class and its subtypes
The particular use case I have is a spatial structure. Say that I have a 2D structure like a quadtree, or a 3D structure like an octree.

Ideally it should support straightforward query and insert methods:

'''
tree.add(element,shape);
List<Element> elements = tree.query(shape);
'''

Shape itself shouldn't matter. For a frustum culling test you'd pass a frustum shape, for some shadowmap culling you might pass an oriented box. Inside of the tree the shapes could be arbitrary, you might insert spheres, boxes, etc. And the tree itself has to support tests between the internal structure (ie, rectangle in case of a quadtree, sphere in case of a sphere tree, etc) and the shapes you insert into it.

The way to abstract the structure from such knowledge is to hide it inside a shape type. The spatial structure only has to know the shapes that compose it, a quadtree is going to have 4 squares for example, but has no direct knowledge of the shapes its storing. Could be storing anything that implements contains/intersects tests with rectangles for example.

Of course you might find this not worthwhile, that could be done differently, and its okay. Just presenting one actual use case I have right now and how I designed my solution. You can probably can come up with a better way that doesn't requires a generic superclass like "Shape" to work.

> That's not JOML. It should be another library. I fear that this is the case here, too.

Yeah, although I'm honestly surprised by the lack of comparable libraries with geometry primitives. LibGDX has some but eh, LibGDX is a bit of a virus, every bit depends on the rest of the library. And it has some very questionable design choices in their math classes for my tastes. Thats why I commented about it here, I find JOML much better in that regard.

> I googled and stackoverflowed a bit for a line segment / rectangle intersection test, and found this solution to be a working one.

Sweet, thanks a lot!

**Comment by chriscamacho** [comment]
"JOML – Java OpenGL Math Library"

surely geometry should be a sub project or even completely different project depending on JOML

I'd kind of thought of JOML as a library for the specific math needed by OpenGL ie matrix and vector manipulation - that could even reach a stage of maintenance only feature completion allowing it to achieve robust stability

As such should it not just stick to that limited sphere and avoid bloat?

**Comment by httpdigest** [comment]
> Yeah, although I'm honestly surprised by the lack of comparable libraries with geometry primitives. 

I agree with you there. I believe the reason for the lack of such generic libraries for spatial acceleration structures like you mentioned is that hardly anyone doing serious business is interested in a clean generic school book implementation. Real implementations being used in engines and games are very likely highly tuned and geared towards very specific use cases and requirements to squeeze the last bit of performance out of them.
I am thinking about caching, assuming temporal coherence, categorizing objects into static and dynamic ones and adjust the implementation accordingly to cater to that situation by maybe not updating the whole spatial acceleration structure but only the parts containing the dynamic objects. I don't know. :)
Then, like I said above, everyone has a different feeling about what should and should not constitute a generic primitive class. Most of the times, those classes also contain auxiliary data for caches of spatial acceleration structures or other information relevant to the engine/game.
I actually experienced this when developing the frustum culling code in JOML: The developer of "We Shall Wake," who helped me drive the design of JOML to become a more usable library, mentioned that a generic "by the book" frustum culling code is unusable for him, because he also makes use of fog/sight-radius in his game. Therefore, his own frustum culling code can also cull against a bounding sphere first.
All those things then make any solution not generic and widely usable/applicable anymore because they are connected strongly with the rest of the library/game/application and its design and requirements.

Then another reason is likely that people doing real business rather choose C/C++ (i.e. a non-garbage collected language) to do such things.

**Comment by dustContributor** [comment]
I understand what you're saying. We can agree in that providing shape classes isn't worth it, but there are a few fundamental things, math things, that don't change between implementations. Sphere-sphere or frustum-aabb intersection won't change between games. 

These functions do constitute the fundamental base of the things you mentioned. And yeah, there are plenty of solutions around but you gotta find them, implement them, and see if they work. Moreover, for someone who doesn't understands much of the math involved its very hard to make it work, nevermind compare them with other solutions to see which is best. And once you got them implemented and working its easier to use them as tools to build bigger things.

It works the same with JOML as currently is. There are plenty of ways in which you can use a mat4-mat4 multiplication, that doesn't means the code for the multiplication itself needs to change. Same with intersection/containment tests. Nobody threw his arms in the air saying "Gah no two people use vector math the same for OpenGL!" and denied the usefulness of a math lib (I hope).

**Comment by httpdigest** [comment]
An up on this one:
I am currently working together with the developers of [We Shall Wake](http://www.weshallwake.com/) to research and implement the best of all sorts of intersection and distance determination algorithms in JOML.
I have to admit that this does stretch the scope of JOML a bit in the direction of a support library for a game and physics engine (not solely for rendering that is).
There are some useful classes which implement very high performance intersection algorithms, especially the 2008 [Fast Ray/Axis-Aligned Bounding Box Overlap Tests using Ray Slopes](http://www.cg.cs.tu-bs.de/media/publications/fast-rayaxis-aligned-bounding-box-overlap-tests-using-ray-slopes.pdf) method. It is particularly well suited when testing many AABs against the same ray.
There are other things, too, in the [Intersectionf](https://github.com/JOML-CI/JOML/blob/intersection/src/org/joml/Intersectionf.java) class.
You might want to check it out. :)

**Comment by dustContributor** [comment]
Sweet! For great justice! \o/

**Comment by kappaOne** [comment]
That does look good, any plans for class that does 2d intersection tests?

**Comment by httpdigest** [comment]
Thanks, kappa! If the need is expressed then yes.

Also the plan is to have the geometry branch with those 3D intersection methods eventually merged into master and doing a new "geometry-2d" branch from joml-2d which will make it back to joml-2d in the end.
Then there is also joml-mini which will always just contain those simple matrix/vector methods that JOML originally set out to support.

This way we would have really only 3 different styles of JOML:
- master: everything related to 3D
- joml-2d: everything related to 2D
- joml-mini: only matrix and vector for 3D

I think there is no real need for a minimal 2D variant, but possible.
So in the end we would categorize between 2D and 3D and this is useful because most classes in master for 3D have no meaning in 2D, and there are some methods in joml-2d which make sense for 2D but not really for 3D, for example Matrix3f.rotate(angle).

So that would be the current plan of organising things. :)

**Comment by httpdigest** [comment]
Also one note again about 2D intersection algorithms:
It turned out that literally _every_ 3D intersection algorithm in the Intersectionf class can also be used for 2D by just keeping the z component constant (like 0.0f).
The performance will of course be better when the unnecessary computations and parameters are removed for dedicated 2D algorithms.

**Comment by httpdigest** [comment]
Okay, 2D intersection is in. See: class [Intersectionf](https://github.com/JOML-CI/JOML/blob/geometry-2d/src/org/joml/Intersectionf.java) in geometry-2d branch.

**Comment by dustContributor** [comment]
Can we get an Intersection2D and an Intersection3D class instead of two versions of the lib? Or just like that right now because its in development yet?

**Comment by httpdigest** [comment]
I see no problem to do that with the intersection methods. Could indeed be useful to have 2D intersection methods in a 3D application with the rest of JOML being 3D.
I merged 2D and 3D intersection methods into Intersectionf/d in the "geometry" branch.
Check out the latest joml-geometry:1.6.9-SNAPSHOT, in case you use Maven/Gradle.

**Comment by dustContributor** [comment]
Thanks! Yeah, I had forgotten about it :smile:

**Pull request closed without merging**
