### PR TITLE
Added get/set methods to all Vector classes that accept ByteBuffer and Float/DoubleBuffer.

### PR DESCRIPTION
**Pull request by ra4king**
All Vector classes now have constructors accepting (ByteBuffer) and (index, ByteBuffer), methods set(ByteBuffer) and set(index, ByteBuffer), and methods get(ByteBuffer) and get(index, ByteBuffer).
All Vector float classes have their respective FloatBuffer versions while Vector double classes have their respective DoubleBuffer versions.

### CODE REVIEW

**Comment by httpdigest** [comment]
Thanks for contributing!
However, please rework all JavaDocs. They do not pass JDK1.8 doclint.
Also the JavaDocs on the constructors seem to be just copy/pasted from the setter/getter methods, as they contain nonsensical "see" references to set methods.
If those issues are fixed, I will merge.

**Comment by ra4king** [comment]
I don't know how those self closing tags got in there as I had copied your other comment which contained a <p> without the self closing slash.... strange.

I fixed the see to the constructor rather than set. Nice catch with that, as this was mostly copy and paste to ensure consistency and I was wondering if I had missed important changes.

**Comment by httpdigest** [comment]
*sigh*... please invoke `mvn javadoc:javadoc` with a JDK8 and see the warnings that doclint still outputs on your changes. :)
Also please have again a thorough (and I do mean _thorough_) look on your JavaDocs. There are words like "orderthis" in them.

**Comment by httpdigest** [comment]
P.S.: You would not believe how much hours I have actually put into the JavaDocs to get them where they are now.
No kidding, about 90% of the total development time of JOML was in the JavaDocs. Writing the little Java methods was nothing compared to that. :)
And I have to say that JOML's JavaDoc documentation is _far_, _far_ away from being what I consider good documentation. But I want to at least uphold this bit of quality on the documentation.
That's why I am maybe being a bit picky here.

**Comment by ra4king** [comment]
Ahh sorry I missed that. I didn't have maven installed but I got it working and the only warnings I saw were the missing @return statements. I don't know how they were missing, my IDE should have generated them O_o

And yeah I don't doubt you, writing javadoc is a time-sucking pain but I completely agree with your insistence on them being of high quality. I am disappointed in myself for having this many mistakes as I thought I had gone through it pretty well :/

I went through the changes carefully and I don't think there are any more typos or issues.

**Comment by httpdigest** [comment]
Now it looks nice. :) Thank you for adding that!

**Pull request merged**
