### PR TITLE
fix for issue #175

### PR DESCRIPTION
**Pull request by mohamed-abdelhameed**
this is a fix for issue #175 
also added 2 test classes to verify the solution

### CODE REVIEW

**Comment by httpdigest** [comment]
Please redo this. The line endings changed from linux `\n` to windows `\r\n` in the files Matrix3d and Matrix3f. See effective diff over all commits via: https://github.com/JOML-CI/JOML/compare/master...mohamed-abdelhameed:master
Please use linux line endings consistently also in the new test classes. Thanks!

**Comment by mohamed-abdelhameed** [comment]
fixed line ending

**Comment by httpdigest** [comment]
I just fixed the line endings of all _other_ source files which still had wrong line endings and added a build-time check. It does not affect any files you edited, so you will be fine with just rebasing your changes onto the current master.

**Comment by mohamed-abdelhameed** [comment]
> I just fixed the line endings of all _other_ source files which still had wrong line endings and added a build-time check. It does not affect any files you edited, so you will be fine with just rebasing your changes onto the current master.

ok , it's ready now

**Pull request merged**
