### PR TITLE
Implemented GWT support

### PR DESCRIPTION
**Pull request by sriharshachilakapati**
I have got this to work successfully with my wrapper using GWT, so here are a list of changes I made:

  - Changed all the get and set methods that operate on NIO buffers to use arrays.
  - Removed the writeObject and readObject methods since GWT doesn't support serialization.
  - Removed the decimal format argument in the toString method since there is no DecimalFormat class in GWT.
  - Modified all the Javadocs to reflect these changes.

### CODE REVIEW

**Comment by httpdigest** [comment]
Okay, two things that I am rather unpleased with and which hinders me to pull this request:
1. About 4,000 of the 4,410 line deletions are unnecessary and disguising the actual essence of what was changed, because those 4,000 lines just remove a single space in some JavaDoc. Please do not do this.
2. I will not merge "Merge pull request #..." commits.

**Comment by sriharshachilakapati** [comment]
Ah, I don't know what to do now. Those pull requests are the result of me updating my fork from the main repository. Should I re-fork your repo and start again?

And regarding the spaces, I don't know what happened to them, I never used the formatter in the project, so it might be that IntelliJ's default settings to remove empty spaces. Will have to check that one.

What should I do now?

**Comment by httpdigest** [comment]
> Ah, I don't know what to do now. Those pull requests are the result of me updating my fork from the main repository. Should I re-fork your repo and start again?

Okay, that is strange. Usually, when I pull the changes from an upstream repository, it will _not_ create merge commits, but rebase instead.

The only way to solve this now is to save your current work, clone the upstream repo again and use WinMerge for example and apply only the essential changes.

**Comment by sriharshachilakapati** [comment]
Okay then, I'll start a new fork and make a new pull request. Closing this now.

**Comment by httpdigest** [comment]
Please take note that I merged my current changes to `master` into `gwt`. This should be a simple rebase/fast-forward on your side, if you already forked/reverted.

**Comment by sriharshachilakapati** [comment]
I have not much experience with git, but my GWT branch is 10 commits behind master. What should I do now? Sorry I have less experience with GIT.

**Pull request closed without merging**
